[project]
name = "esmjax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[tool.ruff.lint]
extend-select = [
    "I", # isort
]
extend-ignore = [
    "F722", # https://docs.kidger.site/jaxtyping/faq/
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=9.0.1",
    "ruff>=0.14.5",
]
